spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/jpa
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
